[[Entwine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "124553ab829ad8f8355acf9be9e46b54014453a8"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "f16d7a6d07a259baefdea4a13a53711ff6a2696e278606b776e7aba62c1a8f3f"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Entwine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26b2276778a72e184edcada29bdadc31b460529f"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "aee4820af8604b62c4636b11ea9318b4e4682e357108a0bac56187c2752e5261"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Entwine]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e04c8ee4fa080fddf42d77917b7873038dc5842c"
libc = "musl"
os = "linux"

    [[Entwine.download]]
    sha256 = "693a1cad83e49e43f7abf4dd4717e5ef87a8fdf48487d946aa8014affed35e9d"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[Entwine]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e5f89005b9ca266b560baff24e1ad769ab1cdef"
libc = "musl"
os = "linux"

    [[Entwine.download]]
    sha256 = "e9076ffaad0bc9f4ee2857bd98d7ca9ccfc102c9b44539155ff496fab8981a9c"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[Entwine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f653359b8d3e57f759ffa6c99255440b31b0ae3d"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "2a498058299808b578881b0125f97951c20ef05d84db320cc465bd8efd984755"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Entwine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a253cdf21fcee5d47d3e316828a0be45420dee0f"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "4750c78ce39e06bb97d0c96b3f275bf87a5cf5279debec82770880b84fa89aab"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Entwine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "daaa2b34d559e771de7624b4e9f3e4d8edc9ca24"
libc = "musl"
os = "linux"

    [[Entwine.download]]
    sha256 = "cbcb444cb4a6476f6745af107f6284612f86920d87fe3fb57da5da559f0a32d0"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Entwine]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72c44d4a07bfe86593f419dc2e4f57e5a636d885"
libc = "musl"
os = "linux"

    [[Entwine.download]]
    sha256 = "d12deeeae72e67140ba057374790105c7974a5d068440f22596358338525b060"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Entwine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "327b9de4c0864c75e89f0484b44c11e29ac1e357"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "0858d7aa5be525d098b973efbcef0006d90d4ff7fb1b73f9d558a6c6e9e8a285"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.i686-linux-gnu-cxx03.tar.gz"
[[Entwine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0259b64a34015620efd8360cba5e53cbcd648dd"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "e1de7f9ffd79341a33b7b2da59cbd8b27ad531b9da7d29131be9dded77cd5d8c"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.i686-linux-gnu-cxx11.tar.gz"
[[Entwine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71a993e464a43b0a98fa5b287d5e98ea2ddd01f1"
libc = "musl"
os = "linux"

    [[Entwine.download]]
    sha256 = "ed390a685c0ab5f6141e4a8d3815fb5170f6019c81fe2b772709193423b260b8"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.i686-linux-musl-cxx03.tar.gz"
[[Entwine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62878acba3d79a05c15caa6c4e74741f9ddff226"
libc = "musl"
os = "linux"

    [[Entwine.download]]
    sha256 = "943a4775d92e0a9e71f964b0bef168aa4f8ee38c277bbc803ec0c6c029c9406b"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.i686-linux-musl-cxx11.tar.gz"
[[Entwine]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfb58b8ce35552393b895e7f526c28f07dbf0ab4"
os = "windows"

    [[Entwine.download]]
    sha256 = "735a3f321cc47bb3d22ea0a94f1d330eb74b5ea7e03ac18ca46e53b6a199c1f0"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[Entwine]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6872d1acca94ccd14bd25e203210c9bb5882aabf"
os = "windows"

    [[Entwine.download]]
    sha256 = "a556c0b1e4b20851db5effceeaed4216042fafb43b807be15136563077c915ab"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[Entwine]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "077075fcdae069a901b00ceb3743e14ec045f83e"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "fcbb914652662e194ef31109ff4a4eba4087378704e484f232be84098cb4e65f"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Entwine]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "470dd93863ee091b79ca3f655d13e7987ab89423"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "0ede0ada291e91581c41c0ebd930b7eb6eb2cb50c68cd25239def7898ef1bfee"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Entwine]]
arch = "x86_64"
git-tree-sha1 = "4792f4e5237abc6f7764726f18a4429f7f31df42"
os = "macos"

    [[Entwine.download]]
    sha256 = "6738a9163d12a24d069662eb7f156e5f9be5e8a70bc3a1c989549f4a314b1505"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.x86_64-apple-darwin.tar.gz"
[[Entwine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08c324e9b45be7b70dab2db562927ecb56e353db"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "2c4271c2e6bed298dce4d82a34ed54f85b1101b008612d204bf0c1b6a7ef11d8"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Entwine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c97d954540db6815968c94aeaa068388e97b165"
libc = "glibc"
os = "linux"

    [[Entwine.download]]
    sha256 = "81de20af9c72c7c50a8a7e7ae1561ead5fed11395b26643d31dd57f44b910080"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Entwine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6d7e318017ae910dd6148e8f05d42aa0c03396e"
libc = "musl"
os = "linux"

    [[Entwine.download]]
    sha256 = "d6f920344a795e04b283010cf3f92855cc2ab853a6135aa526fe0fc5f717a52c"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[Entwine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "703fd361eab88de37aa7f77f9858111191b7639d"
libc = "musl"
os = "linux"

    [[Entwine.download]]
    sha256 = "a7468aec592c7a6e8ad350c53ee518091968e09c89e16951df9c9594944e2b43"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[Entwine]]
arch = "x86_64"
git-tree-sha1 = "9fb1dcc400d3359aa52c85d395ce463434c630ac"
os = "freebsd"

    [[Entwine.download]]
    sha256 = "de4189357a60723b6b6cead40ad1c5b06241a37672a23c704fad14e66a3d452d"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.x86_64-unknown-freebsd.tar.gz"
[[Entwine]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a2f9757ca50d126b7936796f15481b6f74738ea"
os = "windows"

    [[Entwine.download]]
    sha256 = "59c96f731d4215d05289e098c58ad2085b0931bbe7fbe55f972aecdedf3e1ce1"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Entwine]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f20a03169dc2dd2d4f86ec6526b404a7e321021"
os = "windows"

    [[Entwine.download]]
    sha256 = "0a1af434513b84e6119c37e45158da1d60f2254d31238ce3e7b157ce6d599c65"
    url = "https://github.com/JuliaBinaryWrappers/Entwine_jll.jl/releases/download/Entwine-v2.2.0+0/Entwine.v2.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
