# Autogenerated wrapper script for Entwine_jll for x86_64-w64-mingw32-cxx11
export entwine, libentwine

using PDAL_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("Entwine")
JLLWrappers.@declare_executable_product(entwine)
JLLWrappers.@declare_library_product(libentwine, "libentwine.dll")
function __init__()
    JLLWrappers.@generate_init_header(PDAL_jll, OpenSSL_jll)
    JLLWrappers.@init_executable_product(
        entwine,
        "bin\\entwine.exe",
    )

    JLLWrappers.@init_library_product(
        libentwine,
        "bin\\libentwine.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
